/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaNative */

#ifndef _Included_javaNative
#define _Included_javaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaNative
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javaNative_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
